name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
version: 10.2.0
repository: https://github.com/baseflow/flutter-permission-handler
issue_tracker: https://github.com/Baseflow/flutter-permission-handler/issues

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: permission_handler_android
      ios:
        default_package: permission_handler_apple
      macos:
        default_package: permission_handler_apple
      windows:
        default_package: permission_handler_windows

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  permission_handler_android:
    git:
      url: https://github.com/bvoq/flutter-permission-handler.git
      path: permission_handler_android
      ref: master
  permission_handler_apple:
    git:
      url: https://github.com/bvoq/flutter-permission-handler.git
      path: permission_handler_apple
      ref: master
  permission_handler_windows:
    git:
      url: https://github.com/bvoq/flutter-permission-handler.git
      path: permission_handler_windows
      ref: master
  permission_handler_platform_interface:
    git:
      url: https://github.com/bvoq/flutter-permission-handler.git
      path: permission_handler_platform_interface
      ref: master

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1
  plugin_platform_interface: ^2.0.0
